version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - rm -rf gen/
      - mkdir -p gen/go
      - protoc -I . proto/sso/sso.proto 
        --go_out=./gen/go 
        --go_opt=paths=source_relative
        --go-grpc_out=./gen/go 
        --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=./gen/go 
        --grpc-gateway_opt=paths=source_relative

  clean:
    desc: "Clean generated code"
    cmds:
      - rm -rf gen/